# Generated by Django 3.1.2 on 2020-10-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Coin_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.CharField(max_length=50)),
                ('high', models.CharField(max_length=50)),
                ('low', models.CharField(max_length=50)),
                ('close', models.CharField(max_length=50)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coin')),
            ],
        ),
    ]
